# Generated by Django 2.2.9 on 2019-12-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заявка')),
                ('signed', models.DateField(verbose_name='Дата подписи')),
                ('conclusion', models.CharField(max_length=255, verbose_name='Заключение СП')),
                ('conclusion_date', models.DateField(verbose_name='Дата подписи СП')),
                ('ready', models.CharField(max_length=255, verbose_name='Исполнено')),
                ('ready_date', models.DateField(verbose_name='Дата подписи исх.')),
                ('status', models.PositiveIntegerField(choices=[(0, 'нет ТС'), (1, 'в работе'), (2, 'ждем СП'), (3, 'исполнено')], default=0, verbose_name='Статус')),
                ('info', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
